services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    container_name: vulgpt_django
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=vulgpt.settings.production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    container_name: vulgpt_react
    volumes:
      - frontend_static:/usr/share/nginx/html

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx:/etc/nginx:ro
      - frontend_static:/usr/share/nginx/html:ro
      - static_volume:/app/backend/staticfiles:ro
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend

volumes:
  frontend_static:
  static_volume: